# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JjWlAJ8NUyJ3EB3MkWV_eifElEtXvPqf
"""



"""video que explica los objetivos infinitos de pantallas junto a biomecanica con alcances a movimientos, patrones ocuros que explotan vulnerabilidades, fuidez tecnológica

a partir del diseño se secuestra la voluntad de la persona ya sea en videojuegos donde se llenan de elementos químicos donde nos llenan de que nos gusta hacer para no cansarnos al usarlo,
el cerebro reacciona debido a los colores, acciones, etc


leyes ux jhon lawesky
psicología de diseño, historia y factores

porqu las apps son naturales y otras frustan
psicología es la habilida no de diseño mas valiosa

psicología Gestalt

ley de jackobn, el usuario espera que el sistema funcione de manera familiar a las apps diarias
modelos mentales, aprovechar lo familiar
ley de fitts
mecánica física regla de el tiempo que pasamos en la pantalla dependiendo de el tamaño de el botón etc
ética y responsabilidad de la implicación del diseño de el comportamiento



diseño ui regla 80/20: parte del diseño ui es demasiado abstracta, se soluciona teniendo eln cuenta el poprcentaje min de reglas
20 conocimiento que aporta el 80 de resultados
diseño ui practico
regla 80 20
oaleta de colores simple: un solo color con variación de ese mismo color
estructura y espacio: rectángulo dentro de rectángulos entendiendo el modelo de caja, espacios en mul de 8, ser generoso en espacio blanco
diseño basado en lógica: no diseñar solo por lo estético, debe ser menos costo de interacción, interfaz simple reduce el riesgo/ su diseñor es estético o tiene lógica funcional

validación de formularios, borde rojo al icono de advertencia parea personas con daltonismo

diseño e interfaz de usuario: pixeles reales en una pantalla
"""